### ISSUE TITLE
[认证检查] 多控制器下的 Master 控制支持:是否存在 ID 被碰撞的可能性？

### ISSUE THREAD

**Issue by sudoskys** [LlmKira/Openaibot#140]

**Comment by LtD0gE** [comment]
Master在toml里分段配置，由main.py取出后分发至各个controller，controller里把消息传至事件层时已经带上 10x 的ID后缀
应该没有这种问题 :thinking:

**Comment by sudoskys** [comment]
可是校验的时候是校验 realid 的

**Comment by sudoskys** [comment]
> 可是校验的时候是校验 real id 的

**Comment by sudoskys** [comment]
哦对，是分别配置的
