### ISSUE TITLE
docker将来会支持ARM设备吗？

### ISSUE THREAD

**Issue by viyv** [LlmKira/Openaibot#148]
docker版将来会支持arm架构的服务器吗？因为我部署到arm设备无法运行

**Comment by sudoskys** [comment]
https://github.com/LlmKira/Openaibot/issues/138

**Comment by aiastia** [comment]
aiastia/openaibot:main

**Comment by viyv** [comment]
> dockee 三件套😂 arm 和amd 可跑。我甲骨文 arm 占用7G……
> 
> aiastia/blipserver:main
> 
> aiastia/openaibot:main
> 
> aiastia/moegoe:master

我没搞懂拉取哪个……

**Comment by aiastia** [comment]
> aiastia/openaibot:main

aiastia/openaibot:main 

其他的 是插件（🤔

**Comment by viyv** [comment]
> > aiastia/openaibot:main
> 
> 
> 
> 
> 
> 
> 
> 其他的 是插件（🤔

我 pull 过来还是不能用…不知道哪一步出错了

**Comment by aiastia** [comment]
> > > aiastia/openaibot:main
> > 
> > 
> > 其他的 是插件（🤔
> 
> 我 pull 过来还是不能用…不知道哪一步出错了

配置文件？

**Comment by aiastia** [comment]
请在arm上使用git clone将Openaibot仓库克隆到本地，并正确配置Config文件夹下的几个文件，之后将images指定为aiastia/openaibot:main（该镜像支持amd和arm架构）。

**Comment by viyv** [comment]
哦哦，好的我再试试，多谢指点

**Comment by socekin** [comment]
> aiastia/openaibot:main
将images指定为aiastia/openaibot:main，这个应该怎么操作呢？docker小白，请教一下

**Comment by viyv** [comment]
> 



> > aiastia/openaibot:main
> > 将images指定为aiastia/openaibot:main，这个应该怎么操作呢？docker小白，请教一下

编辑clone下来的文件夹里面的docker-compose.yml，把里面的image: aiastia/openaibot:main换成aiastia/openaibot:main，保存，执行docker-compose up -d

**Comment by socekin** [comment]
> > 
> 
> > > aiastia/openaibot:main
> > > 将images指定为aiastia/openaibot:main，这个应该怎么操作呢？docker小白，请教一下
> 
> 编辑clone下来的文件夹里面的docker-compose.yml，把里面的image: aiastia/openaibot:main换成aiastia/openaibot:main，保存

谢谢，成功运行了，但是telegram Bot输入命令没有反应，请教一下master user id是否是填管理员的ID？一串9位的数字？

**Comment by viyv** [comment]
> 
是的

**Comment by viyv** [comment]
> > > 
> > 
> > 
> > > > aiastia/openaibot:main
> > > > 将images指定为aiastia/openaibot:main，这个应该怎么操作呢？docker小白，请教一下
> > 
> > 
> > 编辑clone下面的文件夹里面的docker-compose.yml，把里面的image: aiastia/openaibot:main替​​换成aiastia/openaibot:main，保存
> 
> 谢谢，成功运行了，但是telegram Bot输入命令没有反应，请教一下master user id是不是填管理员的ID？一串9位的数字？



> > 
> 
> 是的

**Comment by aiastia** [comment]
https://llmkira.github.io/Docs/guide/docker

**Comment by sudoskys** [comment]
为什么都要用 docker (不解

**Comment by socekin** [comment]
> 为什么都要用 docker (不解

穷，身边只有能跑docker的设备拿来学习

**Comment by aiastia** [comment]
> 为什么都要用 docker (不解
docker 玩坏了 可以重新来。。。。不然真得重装系统了

**Comment by viyv** [comment]
> > 为什么都要用 docker (不解
> > docker 玩坏了 可以重新来。。。。不然真得重装系统了

安装blipservr 容器无法运行，查看找日志是这个  错误
File "/usr/local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
我找了很多方法都不能决解这个问题，请问有什么办法解决吗？

**Comment by sudoskys** [comment]
> 

调用显卡失败，如果你没有显卡，请使用 cpu 模式

**Comment by viyv** [comment]
> > 
> 
> 调用显卡失败，如果你没有显卡，请使用 cpu 模式

vps 不能调用这个显卡模式的是吧？

**Comment by sudoskys** [comment]
> 

如果有显卡就能，没有就不行，得改 config.toml

**Comment by viyv** [comment]
> > 
> 
> 如果有显卡就能，没有就不行，得改 config.toml

好的，多谢解答

**Comment by aiastia** [comment]
> 

你这是没看教程吧

**Comment by viyv** [comment]
> > 
> 
> 
> 
> 你这是没看教程吧 

看了，没发觉是没显卡的问题…😂
