### ISSUE TITLE
无论是docker环境还是宿主机环境KeyError: 'Controller'无法正常启动

### ISSUE THREAD

**Issue by lauren12133** [LlmKira/Openaibot#149]
日志文件：
2023-02-07 06:31:07.071 | INFO     | __main__:<module>:26 - NEWS Channel:https://t.me/Openaibot_channel
2023-02-07 06:31:07.072 | INFO     | __main__:<module>:28 - 新闻:请使用 `pip install -U llm-kira -i https://pypi.org/simple/` `pip uninstall openai-kira`
Traceback (most recent call last):
  File "/app/main.py", line 51, in <module>
    start()
  File "/app/main.py", line 34, in start
    ctrlConfig = config.Controller
KeyError: 'Controller'
 系统：debian 甲骨文机器

**Comment by lauren12133** [comment]
按照提示两项执行无法解决问题pip install -U llm-kira -i https://pypi.org/simple/ pip uninstall openai-kira

**Comment by sudoskys** [comment]
需要配置配置文件

**Comment by sudoskys** [comment]
如果还有问题，请标 bug 标签

**Comment by lauren12133** [comment]
openaibot-openaibot-1  | 2023-02-07 07:05:40.271 | INFO     | __main__:<module>:26 - NEWS Channel:https://t.me/Openaibot_channel
openaibot-openaibot-1  | 2023-02-07 07:05:40.272 | INFO     | __main__:<module>:28 - 新闻:请使用 `pip install -U llm-kira -i https://pypi.org/simple/` `pip uninstall openai-kira`
openaibot-openaibot-1  | Traceback (most recent call last):
openaibot-openaibot-1  |   File "/app/main.py", line 51, in <module>
openaibot-openaibot-1  |     start()
openaibot-openaibot-1  |   File "/app/main.py", line 42, in start
openaibot-openaibot-1  |     module = importlib.import_module('App.' + starter)
openaibot-openaibot-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
openaibot-openaibot-1  |     return _bootstrap._gcd_import(name[level:], package, level)
openaibot-openaibot-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
openaibot-openaibot-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
openaibot-openaibot-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
openaibot-openaibot-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
openaibot-openaibot-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
openaibot-openaibot-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
openaibot-openaibot-1  |   File "/app/App/Telegram.py", line 20, in <module>
openaibot-openaibot-1  |     from App import Event
openaibot-openaibot-1  |   File "/app/App/Event.py", line 13, in <module>
openaibot-openaibot-1  |     import llm_kira
openaibot-openaibot-1  | ModuleNotFoundError: No module named 'llm_kira'
重新拉取app.toml过后启动依然有报错 这是缺失依赖吗

**Comment by sudoskys** [comment]
没有安装依赖

**Comment by sudoskys** [comment]
pip install llm-kira

**Comment by lauren12133** [comment]
docker-comepose 运行起来后没有自动安装依赖吗？看来需要手动装。。

**Comment by sudoskys** [comment]
> docker-comepose 运行起来后没有自动安装依赖吗？还是说手动装这一步是必须的。。

对Docker不是很熟练... 你可以采用 https://github.com/LlmKira/Openaibot/issues/148#issuecomment-1420189087

**Comment by sudoskys** [comment]
我自身采用的是 sh
