### ISSUE TITLE
[观测] Server Error While Processing Your Prompt

### ISSUE THREAD

**Issue by sudoskys** [LlmKira/Openaibot#150]
https://community.openai.com/t/api-calls-to-davinci-text-3-very-slow-and-random-speeds-for-identical-prompts/51134

**Comment by sudoskys** [comment]
https://community.openai.com/t/continuous-gpt3-api-500-error-the-server-had-an-error-while-processing-your-request-sorry-about-that/42239/

**Comment by Sansui233** [comment]
昨天陆陆续续遇到了贴子说的问题，今天直接Boom……

**Comment by sudoskys** [comment]
正在构造解决方案

**Comment by Sansui233** [comment]
还有一个观察，用 write 续写的发的请求不会出现这个问题，分时间段测试了每次测了十几次都是这样。

**Comment by sudoskys** [comment]
> 还有一个观察，用 write 续写的发的请求不会出现这个问题，分时间段测试了每次测了十几次都是这样。

奇怪，难道是我们构造的内容导致错误？这是服务器bug？

**Comment by Sansui233** [comment]
感觉有可能，裸api无上下文请求还没出问题，我测试是这样的不知道开发者那边。没有细看记忆池的怎么裁的token（主要也看不懂），万一是api还需要整句的valid token（虽然我也想不出token要怎么才能validate）

另外除了无法处理的error，chat有时还会出现一个是 

```
2023-02-07T09:57:26.353231+0000 - ERROR - RUN:Api Error:Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required by check_pairwise_arrays.
```

没开debug，不知道是哪行报错的。

**Comment by sudoskys** [comment]
> 感觉有可能，裸api无上下文请求还没出问题，我测试是这样的不知道开发者那边。没有细看记忆池的怎么裁的token（主要也看不懂），万一是api还需要整句的valid token（虽然我也想不出token要怎么才能validate）
> 
> 另外除了无法处理的error，chat有时还会出现一个是
> 
> ```
> 2023-02-07T09:57:26.353231+0000 - ERROR - RUN:Api Error:Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required by check_pairwise_arrays.
> ```
> 
> 没开debug，不知道是哪行报错的。
> 
> 好像还有时候返回的 im_end 没有被裁掉

我推了一个版本尝试解决此问题

**Comment by aiastia** [comment]
碰到了 Details:Server Error While Processing Your Prompt

**Comment by Sansui233** [comment]
davinci002 貌似一直在 overloaded，003 还是常见的无法处理，感觉还是 Api 不太稳定的样子……

**Comment by sudoskys** [comment]
疑似，，，，，需要转义特殊字符..

**Comment by sudoskys** [comment]
在 200 token 以上会导致错误率陡然升高，然后，就是... 我写了一点bug

**Comment by sudoskys** [comment]
好像真的是特殊符号的问题

**Comment by sudoskys** [comment]
版本 bump 了

**Comment by sudoskys** [comment]
经过逆向库时发现

**Comment by sudoskys** [comment]
> davinci002 貌似一直在 overloaded，003 还是常见的无法处理（和之前情况差不多），感觉还是 Api 不太稳定的样子……

不是不稳定，是他们私货有点多....

**Comment by Sansui233** [comment]
> 经过逆向官方库实现时发现，需要对所有文本进行编码

？？不明觉厉，编码是指 Tokenize 还是啥……不过我切过 1.5.6  用官库版本，今天下午的时候也还是会有Error when processing，但我也不确定是不是有别的没有处理的 Bug

刚才 bump 的版本，感觉短对话变得流畅了一些，每一句都在疯狂接着给我发问，记性还是会有点不太好，不记得倒数第四句的聊天了……对话 33 句 api 错误 23 句，最高记录是重复说 5 次。如果暂时不好解决 Api 的问题的话，也许可以试试重新请求两次，不用马上急着返回错误结果？

**Comment by sudoskys** [comment]
测试完毕，没有其他情况

**Comment by sudoskys** [comment]
> > 经过逆向官方库实现时发现，需要对所有文本进行编码
> 
> ？？不明觉厉，编码是指 Tokenize 还是啥……不过我切过 1.5.6 用官库版本，今天下午的时候也还是会有Error when processing，但我也不确定是不是有别的没有处理的 Bug
> 
> 刚才 bump 的版本，感觉短对话变得流畅了一些，每一句都在疯狂接着给我发问，记性还是会有点不太好，不记得倒数第四句的聊天了……对话 33 句 api 错误 23 句，最高记录是重复说 5 次。如果暂时不好解决 Api 的问题的话，也许可以试试重新请求两次，不用马上急着返回错误结果？
> 
> 最开始用了很久的 [64e4bb](https://github.com/LlmKira/Openaibot/commit/64e4bb429301acd1ab4758274cc92c7b0a66796f) ，那个虽然慢也确实还挺稳定的，而且直观（玄学）上说文采比较好……？

自动重试？

**Comment by sudoskys** [comment]
> > 经过逆向官方库实现时发现，需要对所有文本进行编码
> 
> ？？不明觉厉，编码是指 Tokenize 还是啥……不过我切过 1.5.6 用官库版本，今天下午的时候也还是会有Error when processing，但我也不确定是不是有别的没有处理的 Bug
> 
> 刚才 bump 的版本，感觉短对话变得流畅了一些，每一句都在疯狂接着给我发问，记性还是会有点不太好，不记得倒数第四句的聊天了……对话 33 句 api 错误 23 句，最高记录是重复说 5 次。如果暂时不好解决 Api 的问题的话，也许可以试试重新请求两次，不用马上急着返回错误结果？
> 
> 最开始用了很久的 [64e4bb](https://github.com/LlmKira/Openaibot/commit/64e4bb429301acd1ab4758274cc92c7b0a66796f) ，那个虽然慢也确实还挺稳定的，而且直观（玄学）上说文采比较好……？

机器人的名称对其内容有巨大影响

**Comment by Sansui233** [comment]
> 机器人的名称对其内容有巨大影响

打……打扰了……
<img width="371" alt="Screen Shot 2023-02-09 at 00 26 48" src="https://user-images.githubusercontent.com/27474981/217591183-e63c41ed-6a29-4900-8301-e0e8ee8a467c.png">

总之非常感谢您的开发和回复！很厉害！

**Comment by sudoskys** [comment]
自动重试机制下，很稳定

**Comment by sudoskys** [comment]
https://community.openai.com/t/currently-getting-a-deluge-of-429s-in-a-row/60512
