### ISSUE TITLE
service.json里的redis localhost问题

### ISSUE THREAD

**Issue by socekin** [LlmKira/Openaibot#154]
请问service.json里的redis localhost要修改成什么？我试过redis的宿主机IP和127.0.0.1都不行。
redis和openaibot我使用的是docker安装的，运行报错：

 Error 99 connecting to localhost:6379. Cannot assign requested address.

聊天机器人报错：Error Occur~Maybe Api request rate limit~nya

**Comment by sudoskys** [comment]
> 

好像就是 localhost

**Comment by socekin** [comment]
> 

默认的localhost报错，改其他IP容器直接不能运行

**Comment by chitang233** [comment]
是 `redis`

**Comment by yangzq6887** [comment]
人家这个东西以后是要收钱的，现在就是拿你们当小白鼠，怎么可能给你整个简单的玩意

**Comment by sudoskys** [comment]
> 人家这个东西以后是要收钱的，现在就是拿你们当小白鼠，怎么可能给你整个简单的玩意

不会，我们有很多协作者，协作者的代码都是agpl，如果变更协议需要投票决定。

**Comment by sudoskys** [comment]
> 人家这个东西以后是要收钱的，现在就是拿你们当小白鼠，怎么可能给你整个简单的玩意

主要是我不会 docker ，无法提供帮助

**Comment by caudex2000** [comment]
把localhost 改為redis

**Comment by yangzq6887** [comment]
> > 人家这个东西以后是要收钱的，现在就是拿你们当小白鼠，怎么可能给你整个简单的玩意
> 
> 主要是我不会 docker ，无法提供帮助

嗯，然后就在频道里贴我。真是大气啊。

**Comment by viyv** [comment]
聊天机器人报错：Error OccurMaybe Api request rate limitnya

这个错误我今天一天都是……

**Comment by sudoskys** [comment]
> 聊天机器人报错：Error OccurMaybe Api request rate limitnya
> 
> 这个错误我今天一天都是……

应该是配置问题，看看日志

**Comment by viyv** [comment]
> 
2023-02-10 03:14:07.536 | INFO     | App.Event:MasterCommand:1022 - SETTING:DEL API KEY
2023-02-10 03:14:16.510 | INFO     | App.Event:MasterCommand:1022 - SETTING:DEL API KEY
2023-02-10 03:16:45.170 | INFO     | App.Event:MasterCommand:1015 - SETTING:ADD API KEY
2023-02-10 03:17:33.321 | INFO     | App.Event:MasterCommand:1022 - SETTING:DEL API KEY
2023-02-10 03:17:43.008 | ERROR    | App.Event:Friends:755 - Error 99 connecting to localhost:6379. Cannot assign requested address.
2023-02-10 04:06:15.661 | ERROR    | App.Event:Friends:755 - Error 99 connecting to localhost:6379. Cannot assign requested address.
我觉得应该是redis 不能使用localhost默认，我需要改成公网ip……

**Comment by sudoskys** [comment]
奇怪的....我不懂docker

**Comment by viyv** [comment]
> > 
> 
> 2023-02-10 03:14:07.536 | INFO | App.Event:MasterCommand:1022 - SETTING:DEL API KEY 2023-02-10 03:14:16.510 | INFO | App.Event:MasterCommand:1022 - SETTING:DEL API KEY 2023-02-10 03:16:45.170 | INFO | App.Event:MasterCommand:1015 - SETTING:ADD API KEY 2023-02-10 03:17:33.321 | INFO | App.Event:MasterCommand:1022 - SETTING:DEL API KEY 2023-02-10 03:17:43.008 | ERROR | App.Event:Friends:755 - Error 99 connecting to localhost:6379. Cannot assign requested address. 2023-02-10 04:06:15.661 | ERROR | App.Event:Friends:755 - Error 99 connecting to localhost:6379. Cannot assign requested address. 我觉得应该是redis 不能使用localhost默认，我需要改成公网ip……

我改成公网之后又变成这个错误了
2023-02-10 04:10:11.325 | ERROR    | App.Event:Friends:755 - You can't write against a read only replica.
2023-02-10 04:10:32.046 | ERROR    | App.Event:Friends:755 - You can't write against a read only replica.
2023-02-10 04:11:04.075 | ERROR    | App.Event:Friends:755 - You can't write against a read only replica.
要疯了

**Comment by sudoskys** [comment]
如果能用 pm2 运行推荐 pm2...

**Comment by viyv** [comment]
> 如果能用 pm2 运行推荐 pm2...

    raise LLMException("Why your predict token > set token limit?")
llm_kira.client.types.LLMException: Why your predict token > set token limit?

这个怎么恢复默认，我不知道设置了哪里把这个设置超限了……

**Comment by sudoskys** [comment]
> > 如果能用 pm2 运行推荐 pm2...
> 
>     raise LLMException("Why your predict token > set token limit?")
> llm_kira.client.types.LLMException: Why your predict token > set token limit?
> 
> 这个怎么恢复默认，我不知道设置了哪里把这个设置超限了……

Config json 和 service json 里面

**Comment by viyv** [comment]
> 

是4000吧？改回来还是不行……

**Comment by viyv** [comment]
> > 
> 
> 是4000吧？改回来还是不行……
> 
> 有交流的群吗？进群比较快截图也方便

我知道了是200，不是4000……

**Comment by sudoskys** [comment]
> > > 
> > 
> > 是4000吧？改回来还是不行……
> > 
> > 有交流的群吗？进群比较快截图也方便
> 
> 我知道了是200，不是4000……

config里面的limit是输出limit...
