### ISSUE TITLE
token limit 修改后服务器不响应

### ISSUE THREAD

**Issue by maojoey** [LlmKira/Openaibot#158]
我尝试将  token_limit 从4000改成3000，发现修改后server不工作。改回4000后正常。

这里4000是默认设置不能修改的吗？最近总是报server error错误，我再想是不是这token设置高了。

"backend": {
    "model": "text-davinci-003",
    "token_limit": 3000
  },

**Comment by sudoskys** [comment]
理论上不会，裁剪机制应该有很大弹性

**Comment by sudoskys** [comment]
server error 是openai 最近服务器不稳定导致

**Comment by sudoskys** [comment]
如果你更新到最新，这种情况会大大减少

**Comment by maojoey** [comment]
> server error 是openai 最近服务器不稳定导致

谢谢。这个问题注意到了，已更新最新版，发现如果server error，那么会重试几次。好像是openai对免费的账号（未绑定支付卡）api使用的限制导致的。

另外这个"token_limit" 如果改为3000后，出现的反应并不是server error，而是没有响应日志。改回去后才能正常使用，最新版也是这样的。

**Comment by sudoskys** [comment]
我测试一下

**Comment by sudoskys** [comment]
正在推版本
