### ISSUE TITLE
执行完一键命令后出现一个问题

### ISSUE THREAD

**Issue by AndoKaguya** [LlmKira/Openaibot#163]
x86的服务器，执行完命令后出现下面这个提示，这个需要管吗？
```
========Down==========
rm: cannot remove 'rustup.sh': No such file or directory
```

为了以防万一，我还执行了一次这个指令
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
但依旧出现上面的提示

**Comment by sudoskys** [comment]
不需要管

**Comment by sudoskys** [comment]
另外 pip install -U llm-kira

**Comment by AndoKaguya** [comment]
谢谢~
