### ISSUE TITLE
PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider.

### ISSUE THREAD

**Issue by markwhitey** [LlmKira/Openaibot#164]
log warning:
`/usr/local/lib/python3.9/dist-packages/apscheduler/triggers/interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html`

fix:
https://github.com/agronholm/apscheduler/discussions/570#discussioncomment-3383707

**Comment by sudoskys** [comment]
https://github.com/LlmKira/Openaibot/commit/159643826241f1784c86ae48270a83fbecb25acc
