### ISSUE TITLE
`load_model` does not return WordVectorModel or SupervisedModel any more

### ISSUE THREAD

**Issue by markwhitey** [LlmKira/Openaibot#165]
log warning :
`load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

fix this bug:
- https://github.com/facebookresearch/fastText/issues/1056#issuecomment-1077398495

- https://github.com/facebookresearch/fastText/issues/1056#issuecomment-1278058705

**Comment by sudoskys** [comment]
This fix will be pushed in the next feature release, thank you for your assistance!
