### ISSUE TITLE
[Bug] No module named 'torch'

### ISSUE THREAD

**Issue by fkcptlst** [LlmKira/Openaibot#166]
## 描述

运行`main.py`和`APIServer.py`时出现`ERROR    | App.Event:load_response:390 - RUN:Openai Error:No module named 'torch'`

## 复现步骤

1. 更新Openaibot至[6583f52](https://github.com/LlmKira/Openaibot/commit/6583f524ec3b855e4cfb35034134ba3224204924)
2. 安装`requirements.txt`
3. 更新`llm-kira`至0.4.1
4. 运行main.py
5. 随便给bot发一条消息

**Comment by markwhitey** [comment]
同，安装完torch 资源占用太多了，直接崩
`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu`

**Comment by sudoskys** [comment]
> 同，安装完torch 资源占用太多了，直接崩
> `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu`


{
//...
"backend": {
                "model": "text-davinci-003",
                "similarity_init": True,
                "token_limit": 4000
            },
}
如果运行不起来语义相似模型，配置 service.json similarity_init 为 false 即可

**Comment by sudoskys** [comment]
后续会默认不加载 torch相关，尽量做成server组件...

**Comment by sudoskys** [comment]
这个问题预计一小时后修复

**Comment by sudoskys** [comment]
?

**Comment by sudoskys** [comment]
大概修好了

**Comment by fkcptlst** [comment]
好像`requirements.txt`还少了一个`psutil`

**Comment by sudoskys** [comment]
> 好像`requirements.txt`还少了一个`psutil`

我记得加着的呀

**Comment by fkcptlst** [comment]
哦哦，看到了。可能是我没装起。那我把这个issue close了。
