### ISSUE TITLE
Telegram 好像不能在群里@机器人触发？

### ISSUE THREAD

**Issue by riverscn** [LlmKira/Openaibot#181]
请问是否考虑支持呢？或者应该怎样配置或者修改代码？

**Comment by sudoskys** [comment]
等我 5 分钟

**Comment by riverscn** [comment]
好像@的时候prompt会带上自己的名字（@xxxx），对结果造成影响……

**Comment by sudoskys** [comment]
> 好像@的时候prompt会带上自己的名字（@xxxx），对结果造成影响……

yes

**Comment by riverscn** [comment]
> > 好像@的时候prompt会带上自己的名字（@xxxx），对结果造成影响……
> 
> yes

但这样会干扰时效性问题的结果。特别是如果@xxx带有英文含义的时候。建议触发搜索的时候过滤掉@xxx。

**Comment by sudoskys** [comment]
> 

好

**Comment by riverscn** [comment]
> > 
> 
> 好

其实不光是时效性的内容会受影响，任何内容都有可能，会限制它的发挥。因此，建议在prompt里不要传@xxx，这也符合人们日常使用@的习惯（在一句话开头@往往不参与这句话的语义）

![image](https://user-images.githubusercontent.com/555062/219853562-35b0d543-2de8-410b-b86d-163fb5621bf3.png)

**Comment by sudoskys** [comment]
正在重构
