### ISSUE TITLE
/remind 命令好像不起作用（telegram）

### ISSUE THREAD

**Issue by riverscn** [LlmKira/Openaibot#183]
![image](https://user-images.githubusercontent.com/555062/219291973-7bb7df8d-93c9-428b-9da2-7d2accbcdd6d.png)

![image](https://user-images.githubusercontent.com/555062/219292022-2f1cee7f-4d53-4c37-aca9-ce33bbd15396.png)

**Comment by sudoskys** [comment]
有效的

**Comment by sudoskys** [comment]
可能大模型抽了什么风吧，在依赖库的下一个版本会做保护措施

**Comment by riverscn** [comment]
补充，确实有用的。确实是大模型的锅，要不要表现出人设看它心情……
![image](https://user-images.githubusercontent.com/555062/219315484-458d3f0a-94bb-4303-b271-3310cf58eeb7.png)
