### ISSUE TITLE
'str' object has no attribute 'time'

### ISSUE THREAD

**Issue by riverscn** [LlmKira/Openaibot#187]
类似于

`2023-02-18 14-19-17: 2023-02-18 14:19:17.503 | ERROR    | App.Event:load_response:380 - RUN:Openai Error:'str' object has no attribute 'time'`

**Comment by riverscn** [comment]
还会返回 Details:Unknown Error

**Comment by riverscn** [comment]
知道了，需要把数据库重置

**Comment by riverscn** [comment]
不行，数据库重置后还是报错

**Comment by sudoskys** [comment]
我在测试

**Comment by sudoskys** [comment]
尝试修复了此问题，请更新逝世？

**Comment by sudoskys** [comment]
下个版本会强制断言，以隔绝此问题

**Comment by sudoskys** [comment]
因为强制校验了输入类型，此问题不应出现
