### ISSUE TITLE
我需要怎么设置才可以让机器人给我发图片呢？

### ISSUE THREAD

**Issue by Checkra2n** [LlmKira/Openaibot#188]
我让机器人给我发个猫咪的图片，结果给我发了一串文字
[图片：一只猫咪]  =.=

**Comment by sudoskys** [comment]
对啊，它不会发图片，这涉及到需求分类

**Comment by sudoskys** [comment]
也不是不可以，但是一是多语言 NLP 模型很难找到，二是运行模型对服务器要求不小
