### ISSUE TITLE
搜索插件似乎不起作用了

### ISSUE THREAD

**Issue by riverscn** [LlmKira/Openaibot#189]
如题

**Comment by sudoskys** [comment]
加了一层条件来着，要带着疑问词才行什么的

**Comment by sudoskys** [comment]
稍后会测试一下

**Comment by sudoskys** [comment]
不行,我网络爆炸了，测不了，但是应该是没问题的

**Comment by sudoskys** [comment]
改进了一下

**Comment by sudoskys** [comment]
依赖库已经推进版本

**Comment by riverscn** [comment]
![image](https://user-images.githubusercontent.com/555062/219922612-84cdc6ac-6a77-4b98-8d07-0decedbb0047.png)

第二个回答是最新版本的效果
第一个回答是 128e161eb9ca8d4d8f60574a3c33b45f18585b96 这个commit的效果
可以看到，之前的版本能比较好利用搜索结果，新的版本不行，傻了很多

**Comment by sudoskys** [comment]
我擦，我忘了给结果切片了

**Comment by sudoskys** [comment]
又推了一个版本

**Comment by sudoskys** [comment]
> ![image](https://user-images.githubusercontent.com/555062/219922612-84cdc6ac-6a77-4b98-8d07-0decedbb0047.png)
> 
> 第一个回答是最新版本的效果 第二个回答是 [128e161](https://github.com/LlmKira/Openaibot/commit/128e161eb9ca8d4d8f60574a3c33b45f18585b96) 这个commit的效果 可以看到，之前的版本能比较好利用搜索结果，新的版本不行，傻了很多

底层框架重构了，利用方式也变了，效果待测

**Comment by sudoskys** [comment]
测试显示此问题已被修复

**Comment by riverscn** [comment]
> 测试显示此问题已被修复
> 
> 在 llm-kira==0.6.1 时

我测试还是不行欸

![image](https://user-images.githubusercontent.com/555062/219937512-331114b7-9237-4c24-ac58-be96601aa9d0.png)

![image](https://user-images.githubusercontent.com/555062/219937526-22576e86-2eb0-4747-aab2-4c8b6a5d2c68.png)

**Comment by sudoskys** [comment]
此问题需要继续修复
提高筛选质量
实现话题切池

**Comment by sudoskys** [comment]
此问题已经被修复，我向优化器引入了初始权重

**Comment by riverscn** [comment]
不行欸，我测试了，然后只能又回滚了

![image](https://user-images.githubusercontent.com/555062/220355411-ba98f2f7-4ba8-410c-af92-d55ecf7e2289.png)

**Comment by sudoskys** [comment]
> 然后只能又回滚了

啊这，现在大概没问题了吧

**Comment by riverscn** [comment]
> > 然后只能又回滚了
> 
> 啊这，现在大概没问题了吧

就是现在的这个有问题

**Comment by sudoskys** [comment]
确认了，是我写的bug.类型str后插入导致的优化器爆炸

**Comment by sudoskys** [comment]
![Screenshot_20230221_214129](https://user-images.githubusercontent.com/75739606/220361593-fbc4cc1d-6859-41eb-8c24-1725178a7496.png)
稍后更新一下

**Comment by sudoskys** [comment]
https://github.com/LlmKira/Openaibot/issues/195

**Comment by riverscn** [comment]
> #195

测试了，还是不行

![image](https://user-images.githubusercontent.com/555062/220522021-c3151dbe-3dcf-4866-aa91-51c76e493ed5.png)

**Comment by cachexy123** [comment]
对的,我也有这个问题

**Comment by sudoskys** [comment]
机制改进导致了负优化，还在继续优化
