### ISSUE TITLE
关于style和remind

### ISSUE THREAD

**Issue by Fangliding** [LlmKira/Openaibot#194]
我反复读了好几遍文档，试了好久，好像并没有理解这两个命令有什么作用，能不能在文档给出更具体解释或者example
以及能不能支持自定义bot的自我设定比如名字，爱好什么的，或许有只是我不知道()

**Comment by sudoskys** [comment]
remind 是强制附加的上文。

style 是字符级别的权重调整（效果不可控

机器人初始化会自动获取自己的名称，信息，你只需要改动机器人账户就可以

**Comment by sudoskys** [comment]
Remind 的效果可能不太稳定来着，这个问题嘛等我再迭代吧

**Comment by sudoskys** [comment]
采用微软架构真是负优化了

**Comment by sudoskys** [comment]
目前没有给全局的设置呢，每个人可以自定义背景内容

**Comment by sudoskys** [comment]
如果有其他疑问请再次激活此 Issue

**Comment by Fangliding** [comment]
> remind 是强制附加的上文。
> 
> style 是字符级别的权重调整（效果不可控
> 
> 机器人初始化会自动获取自己的名称，信息，你只需要改动机器人账户就可以

这两个命令是对单个对话有效还是对单个用户有效，会不会被forgetme清除呢

**Comment by sudoskys** [comment]
> > remind 是强制附加的上文。
> > style 是字符级别的权重调整（效果不可控
> > 机器人初始化会自动获取自己的名称，信息，你只需要改动机器人账户就可以
> 
> 这两个命令是对单个对话有效还是对单个用户有效，会不会被forgetme清除呢

用户

**Comment by sudoskys** [comment]
> > remind 是强制附加的上文。
> > style 是字符级别的权重调整（效果不可控
> > 机器人初始化会自动获取自己的名称，信息，你只需要改动机器人账户就可以
> 
> 这两个命令是对单个对话有效还是对单个用户有效，会不会被forgetme清除呢

不会
