### ISSUE TITLE
刚刚update，出现了一些错误提示

### ISSUE THREAD

**Issue by AndoKaguya** [LlmKira/Openaibot#196]
刚刚看到tg频道通知，然后对bot进行一次update，服务端出现了一个错误提示
`2023-02-21 23:28:38.533 | ERROR    | App.Event:load_response:381 - RUN:Openai Error:list index out of range`

机器人输出
`Details:Unknown Error`

目前无法正常使用，请问这个问题要怎么解决呢

**Comment by sudoskys** [comment]
在排查，可以尝试 pip install -U llm-kira

**Comment by AndoKaguya** [comment]
> 在排查，可以尝试 pip install -U llm-kira

嗯，谢谢，不过在这之前已经使用这个命令了。
有个现象有点奇怪，我接着把bot重启了一次，可以正常回复内容了，但是只回复第一句，后面再问问题，就没反应了，而服务端上也没显示任何内容。
接着又把bot重启一次，可以正常回复了，后续再问问题也会回答，但连续问了几个之后，又是没反应了，服务端也是没东西显示。

**Comment by sudoskys** [comment]
[0.6.46](https://github.com/LlmKira/llm-kira/releases/tag/0.6.46)

**Comment by sudoskys** [comment]
https://github.com/LlmKira/llm-kira/commit/0ecf3b279ce052d76fe9f593d20d08bc910c78ae
