### ISSUE TITLE
Unclosed client session问题

### ISSUE THREAD

**Issue by cachexy123** [LlmKira/Openaibot#197]
用新的服务器搭建时遇到Unclosed client session问题

错误日志
0|bot main  | 2023-02-22 16-01-34: 2023-02-22 16:01:34.614 | INFO     | App.Event:CreateLLM:82 - Using Openai Api
0|bot main  | 2023-02-22 16-01-34: 2023-02-22 16:01:34.637 | SUCCESS  | App.Telegram:run:187 - APP:Telegram Bot Start
0|bot main  | 2023-02-22 16-01-35: 2023-02-22 16:01:35.152 | SUCCESS  | utils.Setting:access_telegram:59 - Init Telegram Bot Profile: {'bot_id': , 'bot_name': '', 'mentions': ''}
0|bot main  | 2023-02-22 16-01-35: Unclosed client session
0|bot main  | 2023-02-22 16-01-35: client_session: <aiohttp.client.ClientSession object at 0x7fce8f1cf3a0>
0|bot main  | 2023-02-22 16-01-35: 2023-02-22 16:01:35.769 | INFO     | __main__:<module>:25 - NEWS Channel:https://t.me/Openaibot_channel

然后就不断的重复,cpu一直占满

**Comment by sudoskys** [comment]
这个问题很玄学，我这边是网络问题。
你排查一下？

**Comment by cachexy123** [comment]
我现在正在排查,刚刚用另外一台新的服务器没有问题,这台却有问题

**Comment by sudoskys** [comment]
一就是先 python3 main.py 启动测试，就不会占满了

**Comment by cachexy123** [comment]
ip问题,已确定

**Comment by lsq960124** [comment]
> ip问题,已确定

大佬方便具体说说么？ 我不太清楚是什么ip问题，我应该也遇到了这样的问题。

**Comment by sudoskys** [comment]
> > ip问题,已确定
> 
> 大佬方便具体说说么？ 我不太清楚是什么ip问题，我应该也遇到了这样的问题。

与你的网络情况有关系。网络条件差/地区条件差/Telegram服务故障等情况，Telegram的 Bot HttpApi 有可能会丢失响应。
- 国内/国内
- 服务器地区
- 是否使用代理

解决办法：修复网络
