### ISSUE TITLE
openaibot_openaibot_1 exited with code 1

### ISSUE THREAD

**Issue by hanwsf** [LlmKira/Openaibot#202]
openaibot_1  | 2023-02-28 14:03:34.264 | INFO     | __main__:<module>:25 - NEWS Channel:https://t.me/Openaibot_channel
openaibot_1  | Traceback (most recent call last):
openaibot_1  |   File "/app/main.py", line 31, in <module>
openaibot_1  |     config = ReadConfig().parseFile(CONFIG_FILE)
openaibot_1  |   File "/app/utils/Base.py", line 69, in parseFile
openaibot_1  |     data = rtoml.load(open(paths, 'r'))
openaibot_1  |   File "/usr/local/lib/python3.10/site-packages/rtoml/__init__.py", line 26, in load
openaibot_1  |     return loads(toml)
openaibot_1  |   File "/usr/local/lib/python3.10/site-packages/rtoml/__init__.py", line 35, in loads
openaibot_1  |     return _rtoml.deserialize(toml)
openaibot_1  | _rtoml.TomlParsingError: duplicate key: `proxy` for key `Controller.QQ` at line 28 column 1
openaibot_openaibot_1 exited with code 1

**Comment by LtD0gE** [comment]
配置里加了多个proxy，删一个

**Comment by sudoskys** [comment]
app.toml 配置错误
