### ISSUE TITLE
Support read pdf and html/link

### ISSUE THREAD

**Issue by sudoskys** [LlmKira/Openaibot#204]

**Comment by sudoskys** [comment]
抽离出ID计算函数，然后添加对文件类型的hook

**Comment by sudoskys** [comment]
非结构化库会引入几个大模型，该库目前还不稳定

**Comment by maojoey** [comment]
期待！！！会有对学术论文的PDF的专门优化吗？学术论文一般是双栏，或者那种有水印有行号的，会影响read的质量么？

**Comment by sudoskys** [comment]
就是针对学术论文的优化

**Comment by sudoskys** [comment]
还在测试 ... 为什么Python库这么喜欢引入超大模型 ...

**Comment by sudoskys** [comment]
https://github.com/Unstructured-IO/unstructured/issues/311

**Comment by sudoskys** [comment]
此项内容需要等待插件进度

**Comment by sudoskys** [comment]
写了半天，早就做了
