### ISSUE TITLE
QQ连不上，请问docker显示这些内容，如何从web页检查？

### ISSUE THREAD

**Issue by hanwsf** [LlmKira/Openaibot#205]
openaibot_1  | 2023-03-01 14:02:09.431 | INFO     | __main__:<module>:25 - NEWS Channel:https://t.me/Openaibot_channel
openaibot_1  | 2023-03-01 14:02:09.463 | SUCCESS  | __main__:start:44 - Set Controller QQ.
openaibot_1  | 2023-03-01 14:03:41.565 | INFO     | App.Event:CreateLLM:82 - Using Openai Api
openaibot_1  | 2023-03-01 14:03:41.850 | INFO     | App.QQ:run:62 - APP:QQ Bot Close
openaibot_1  | 2023-03-01 14:03:41.851 | SUCCESS  | __main__:start:44 - Set Controller BaseServer.
openaibot_1  | 2023-03-01 14:03:41.944 | INFO     | App.BaseServer:run:15 - Base Server Start
openaibot_1  | INFO:     Started server process [1]
openaibot_1  | INFO:     Waiting for application startup.
openaibot_1  | INFO:     Application startup complete.
openaibot_1  | INFO:     Uvicorn running on http://127.0.0.1:9559 (Press CTRL+C to quit)

**Comment by sudoskys** [comment]
openaibot_1 | 2023-03-01 14:03:41.850 | INFO | App.QQ:run:62 - APP:QQ Bot Close

你没有配置 QQ 的 账号相关信息
