### ISSUE TITLE
不能在浏览器浏览Uvicorn base brower

### ISSUE THREAD

**Issue by hanwsf** [LlmKira/Openaibot#210]
openaibot_1  | INFO:     Started server process [1]
openaibot_1  | INFO:     Waiting for application startup.
openaibot_1  | INFO:     Application startup complete.
openaibot_1  | INFO:     Uvicorn running on http://127.0.0.1:9559 (Press CTRL+C to quit)

This site can’t be reached127.0.0.1 refused to connect.

# 基础对话事件服务器，Web支持--还是理解错了，仅用于音响？

**Comment by sudoskys** [comment]
http://127.0.0.1:9559/docs

**Comment by hanwsf** [comment]
http://127.0.0.1:9559/docs  还是访问不了

**Comment by sudoskys** [comment]
> http://127.0.0.1:9559/docs 还是访问不了

本地机器运行服务器，然后在本地浏览器打开调试来着。不应该失败。

**Comment by sudoskys** [comment]
应该是 Docker 的问题
