### ISSUE TITLE
对话内容比较长了后对话上下文会出现奇怪的内容

### ISSUE THREAD

**Issue by wqrqwerqrw** [LlmKira/Openaibot#216]
RT
前面都是正常的角色扮演,之后就感觉对话怪怪的,抓了下网络请求发现了些奇怪的东西,看起来是搜索结果?
![8EE95135BFBFD5E3ABDF2D9449CEC0A2](https://user-images.githubusercontent.com/42306566/222910340-c409ef89-6883-4119-a350-74d3c494a8eb.png)

**Comment by wqrqwerqrw** [comment]
好吧...我悟了, 只要有类似"什么"/"怎么"之类的词就会调用搜索引擎插到最前面作为知识库
```python
                try:
                    if len(_prompt.text) > 5 and Detect().isQuery(_prompt.text):
                        _result = await prompt.build_skeleton(query=_prompt,
                                                              llm_task="Summary Text" if len(
                                                                  _prompt.text) > 20 else None,
                                                              skeleton=random.choice([SearchCraw(), DuckgoCraw()])
                                                              )
                except Exception as e:
                    logger.warning(e)
                for item in _result:
                    prompt.insert_knowledge(knowledge=item)
```

**Comment by sudoskys** [comment]
需要开关吗

**Comment by wqrqwerqrw** [comment]
> 需要开关吗

在config里加个吗，周末的话我可以尝试搞一下，不过我python不是很熟悉，到时候需要帮忙review下

**Comment by wqrqwerqrw** [comment]
另外我在考虑要不要搞个 /raw_remind ，避免现在/remind里的文本替换
感觉这样能更定制化一下，比如之前我想改下机器人的名字还得改源码

**Comment by sudoskys** [comment]
不用，会从框架那边解决

**Comment by sudoskys** [comment]
机器人名字是获取实时机器人自己的名字。但是在使用 Gpt3.5 ，人称被省略了。

**Comment by wqrqwerqrw** [comment]
> 机器人名字是获取实时机器人自己的名字。但是在使用 Gpt3.5 ，人称被省略了。

没有忽略吧，我看有在post请求的json里。主要是角色扮演的时候“xxx_bot“有点出戏

**Comment by sudoskys** [comment]
> > 机器人名字是获取实时机器人自己的名字。但是在使用 Gpt3.5 ，人称被省略了。
> 
> 没有忽略吧，我看有在post请求的json里。主要是角色扮演的时候“xxx_bot“有点出戏

奇怪，我记得是啊

**Comment by wqrqwerqrw** [comment]
> > > 机器人名字是获取实时机器人自己的名字。但是在使用 Gpt3.5 ，人称被省略了。
> > 
> > 
> > 没有忽略吧，我看有在post请求的json里。主要是角色扮演的时候“xxx_bot“有点出戏
> 
> 奇怪，我记得是啊

https://github.com/LlmKira/Openaibot/blob/1a2080d2c35f9f92b3ccac6bae8f547fa50beba5/App/Event.py#L499

**Comment by sudoskys** [comment]
这个是还在 GPT3 版本时候的兼容设计，但是 3.5 不支持定义更多角色
