### ISSUE TITLE
Telegram 支持流式输入

### ISSUE THREAD

**Issue by riverscn** [LlmKira/Openaibot#218]
看到一个例子

https://user-images.githubusercontent.com/555062/222943855-158e8564-820a-4877-8c4c-c99023b338df.MP4

**Comment by sudoskys** [comment]
由于本项目是多平台兼容的，不能保证所有平台都支持流式传输。

**Comment by h1xy** [comment]
我试了以下，流式输入太频繁触发电报API rate limit了，能调低流式输入频率吗
