### ISSUE TITLE
人设在使用 gpt-3.5-turbo 时不起作用

### ISSUE THREAD

**Issue by sider2vf** [LlmKira/Openaibot#229]
如果使用 `text-davinci-003` ，它能够正确接受人设并依据人设回答问题，当询问 `你是谁` 的时候会根据人设信息进行正确回答，以及作出一些简单的判断。
当使用 `gpt-3.5-turbo` 时，使用 `/remind` 并发起新对话，它会始终回复类似 `我是一个AI语言模型，可以通过自然语言处理技术与人类进行交互。我被设计用来回答各种问题，包括但不限于回答常识问题、提供建议和帮助解决问题。` 这样的文本，并不会根据人设的内容针对性地回答问题，输出的结果和没有人设的情况下没有差异。另一句它特别喜欢说的话是 `作为一个AI语言模型，我不能对政治人物或敏感话题进行评价或发表任何政治观点。请您理解。` 有一种言论自由的美（我已经确定关闭了 `Openai TosApi过滤` 和 `简繁关键词过滤` ）

**Comment by LtD0gE** [comment]
OpenAI不喜欢cosplay，在gpt3.5 turbo中似乎对cosplay进行了额外封堵。可能是OpenAI Staff在ChatGPT公测期被CyanNAI的猫娘调教日记里冲死了

**Comment by wqrqwerqrw** [comment]
在system类型中填入的字段是能进行cosplay的吧,我都玩了很久了 可以在playground试试

> OpenAI不喜欢cosplay，在gpt3.5 turbo中似乎对cosplay进行了额外封堵。可能是OpenAI Staff在ChatGPT公测期在CyanNAI的猫娘调教日记里冲死了

**Comment by LtD0gE** [comment]
> 在system类型中填入的字段是能进行cosplay的吧,我都玩了很久了 可以在playground试试
> 
> > OpenAI不喜欢cosplay，在gpt3.5 turbo中似乎对cosplay进行了额外封堵。可能是OpenAI Staff在ChatGPT公测期在CyanNAI的猫娘调教日记里冲死了

但是仅在日常对话里能遵守cosplay，讨论正经事的时候又变回去了

**Comment by sudoskys** [comment]
> 如果使用 `text-davinci-003` ，它能够正确接受人设并依据人设回答问题，当询问 `你是谁` 的时候会根据人设信息进行正确回答，以及作出一些简单的判断。
> 当使用 `gpt-3.5-turbo` 时，使用 `/remind` 并发起新对话，它会始终回复类似 `我是一个AI语言模型，可以通过自然语言处理技术与人类进行交互。我被设计用来回答各种问题，包括但不限于回答常识问题、提供建议和帮助解决问题。` 这样的文本，并不会根据人设的内容针对性地回答问题，输出的结果和没有人设的情况下没有差异。另一句它特别喜欢说的话是 `作为一个AI语言模型，我不能对政治人物或敏感话题进行评价或发表任何政治观点。请您理解。` 有一种言论自由的美（我已经确定关闭了 `Openai TosApi过滤` 和 `简繁关键词过滤` ）

如你所见，3.5模型是过度微调的商业模型。

**Comment by sider2vf** [comment]
今天经过我的测试，我认为应该重新开启此 issue ，我认为可能是API调用方法与 `davinci-003` 有所区别造成的，在 Open AI Playground 的测试中我发现了区别，很显然 `gpt-3.5-turbo` 并不是通过请求头或者在对话中强调他是某某某来进行人设设定的。
以下是 `text-davinci-003` 和 `gpt-3.5-turbo` 在 playground 中的区别
![text-davinci-003](https://user-images.githubusercontent.com/116246824/224482096-4696b79e-a1c9-412e-8115-c72f81507cbb.png)
![gpt-3.5-turbo](https://user-images.githubusercontent.com/116246824/224482201-e3cd172e-3288-4087-94a1-0b819d8473a4.png)
我在 `SYSTEM` 中输入人设文本并开始对话，它将变得正常，所以我怀疑是程序本身的问题

**Comment by sudoskys** [comment]
在框架内部，remind是进入system的。

**Comment by sudoskys** [comment]
造成此问题的原因是Openai，文档说，目前的模型对system并不会过多关注。
