### ISSUE TITLE
Azure OpenAI支持

### ISSUE THREAD

**Issue by CoderChang65535** [LlmKira/Openaibot#233]
默认配置文件中似乎没有Azure OpenAI的配置项
`  "backend": {
    "type": "chatgpt",
    "openai": {
      "model": "text-davinci-003",
      "token_limit": 4000
    },
    "chatgpt": {
      "model": "gpt-3.5-turbo",
      "token_limit": 4000
    }
  }`

**Comment by sudoskys** [comment]
我的电脑掉进池塘里面了，你需要等一天我才能开始为此编码。

同时会改进

**Comment by LtD0gE** [comment]
主播啊，这个是要Azure企业号，要严查企业信息的（
你莲都开不出来  咱还是 先玩着OpenAI API吧

**Comment by LtD0gE** [comment]
有其它问题再reopen

**Comment by CoderChang65535** [comment]
> 有其它问题再reopen

啊，咋就关了...

**Comment by sudoskys** [comment]
> 主播啊，这个是要Azure企业号，要严查企业信息的（
> 你莲都开不出来  咱还是 先玩着OpenAI API吧

没号也可以适配。

**Comment by LtD0gE** [comment]
> > 主播啊，这个是要Azure企业号，要严查企业信息的（
> > 你莲都开不出来  咱还是 先玩着OpenAI API吧
> 
> 没号也可以适配。

人家只给企业爷放API权限啊......个人号连key都拿不到

**Comment by LtD0gE** [comment]
适配的时候怎么测试

**Comment by sudoskys** [comment]
没事，虚空适配

**Comment by sudoskys** [comment]
框架上游已经完成了这项任务
