### ISSUE TITLE
vits服务端报错

### ISSUE THREAD

**Issue by Fangliding** [LlmKira/Openaibot#235]
MoeGoe那个项目没有issue区 我就搬这来了()
报错
TOO MANY SPEAKERS
2023-03-16 16:03:47.363 | ERROR    | server:tts:46 - 'NoneType' object is not iterable
模型我事在这里面找的一个 config.json也是搬的
https://huggingface.co/spaces/sayashi/vits-models/tree/main

**Comment by sudoskys** [comment]
原作者预留了这个错误，我也不明白这种所有模型的speaker集合在一起的算什么

**Comment by Fangliding** [comment]
> 原作者预留了这个错误，我也不明白这种所有模型的speaker集合在一起的算什么

我去那个项目反馈让我找服务端项目的作者()
我对vits不了解，我尝试删掉一个speaker就会报错，而且我把speaker全转换成中文里面甚至没我要的人()

**Comment by sudoskys** [comment]
我到时候看看！

**Comment by sudoskys** [comment]
此校验被尝试去除，可以再试试？

**Comment by sudoskys** [comment]
https://github.com/LlmKira/VitsServer

后续会转为专门开发的推理服务器
