### ISSUE TITLE
amd64 docker安装出现 pycorrector 缺失

### ISSUE THREAD

**Issue by hpcex** [LlmKira/Openaibot#238]
amd64 debian11 用docker安装。

```
apt install docker.io -y
curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod a+x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/dc
dc -v

git clone https://github.com/LLMKira/Openaibot
cd Openaibot/Config

把 app.toml 和 service.json 放到 Config 目录里

dc up -d
```

redis 容器正常起来，但主容器起不来，用docker logs看log，发现pycorrector缺失。
但看了docker文件，都是对的，奇怪。

![1](https://user-images.githubusercontent.com/2332112/226099968-2d7312ad-335a-4df0-8e28-35cb594a1b3c.jpg)

![2](https://user-images.githubusercontent.com/2332112/226099977-740bbd1c-5949-4090-bf6b-565e94119626.jpg)

![3](https://user-images.githubusercontent.com/2332112/226099984-da3265c6-6535-4911-9097-ad614c1c810d.jpg)

**Comment by sudoskys** [comment]
此依赖被移除.
