### ISSUE TITLE
能否批量刪除所有白名單用戶呢?

### ISSUE THREAD

**Issue by G-Sea** [LlmKira/Openaibot#245]
看了文檔/del_white_user只可以刪除指定的多個白名單用戶，但想刪除數十個用戶依然是得手動一個一個加入填，得花蠻多時間

**Comment by sudoskys** [comment]
操作本机 redis 数据库或者，等我写一个小命令？

**Comment by G-Sea** [comment]
> 操作本机穿红衣数据库或者，等我写一个小命令？

等你啦

**Comment by sudoskys** [comment]
https://github.com/LlmKira/Openaibot/commit/5e83f35abe80e18b3b7fa0fa72deccb3b14da80f
