### ISSUE TITLE
【功能请求】加入AI回复流式传输

### ISSUE THREAD

**Issue by GaiZhenbiao** [LlmKira/Openaibot#249]
能否参考[tgGPT](https://github.com/MZhao-ouo/tgGPT)，加入AI回复流式传输功能？

**Comment by sudoskys** [comment]
流式传输这项功能的话，在高并发场景下会触发 API 限制。

**Comment by sudoskys** [comment]
我们正在脱离AI请求相关逻辑到独立的轻量SDK，有望支持流式

**Comment by sudoskys** [comment]
新架构不兼容此特性
