### ISSUE TITLE
这个管理员qq怎么填

### ISSUE THREAD

**Issue by seagullz4** [LlmKira/Openaibot#253]
# 你的QQ号码

是直接填master= 123456
还是master = [123456]

还有一个信息，当我给机器人发信息是却给我显示Check the settings to find that you is not whitelisted!...Group NOT in WHITE list  这段错误消息

**Comment by sudoskys** [comment]
管理员和白名单是隔离的，你是管理员不代表你是白名单。
这里如实填写即可
