### ISSUE TITLE
不能使用第三方api 吗 

### ISSUE THREAD

**Issue by aiastia** [LlmKira/Openaibot#265]
RT 比如使用 API2D 这种

**Comment by sudoskys** [comment]
项目依赖 Openai 推出的 Func calling 特性实现任何插件相关系统，如果不能Func calling，则只能普通的回应消息。

Message 的数据类是按照Openai适配的。

另外我不太了解你提到了两种平台。

**Comment by aiastia** [comment]
https://github.com/songquanpeng/one-api

这种

**Comment by sudoskys** [comment]
忘记写了，OPENAI_API_ENDPOINT 是可以用于 .env 的

**Comment by sudoskys** [comment]
目前还有一点点小问题，需要等等我
