### ISSUE TITLE
[Controller] QQ bot via ~~go-cqhttp~~

### ISSUE THREAD

**Issue by FrostleafChan** [LlmKira/Openaibot#270]
代码要一行一行写，
显卡要一刀一刀切，
PPT要一张一张放。

单个功能自出现在Issue之日起三年内开发完毕（x

**Comment by sudoskys** [comment]
请将你的pull request与此issue关联，并标记为draft

**Comment by sudoskys** [comment]
上游依赖事件

https://github.com/Mrs4s/go-cqhttp/issues/2471
